### ISSUE TITLE
Leg shadow moves and changes shape on ungrouping

### ISSUE THREAD

**Issue by ifohancroft** [garrett/Tux#4]
When ungrouping Tux.svg in Inkscape, the shadow of Tux' right leg that sits on his tummy, moves away to the right a couple hundred pixels and completely changes its shape.

**Comment by ifohancroft** [comment]
I have found the cause and a fix but I want to understand it fully, before submitting a PR, to make sure there aren't any ramifications from the fix.

Btw, the problem is caused by the value of inkscape:original-d of the path of the shadow for the right leg. If the value is changed to be the same as the value of d, then the issue is no longer present. However, I don't yet understand LPE fully, so I am not sure if there will be any ramifications from modifying inkscape:original-d.

**Comment by garrett** [comment]
Thanks again for reporting this and providing a fix!

**Comment by ifohancroft** [comment]
> Thanks again for reporting this and providing a fix!

Since I forgot to reply:
Most welcome! Thank you for redrawing Tux beautifully in vector!
